### PR TITLE
Add global '--no-cache' option

### PR DESCRIPTION
**Pull request by baurmatt**

### CODE REVIEW

**Review by worldworm — COMMENTED** [review]
Wouldn't it be more consistent to call the variable and the flag "no-cache" like restic does?

Disclaimer: This makes it a bit harder to understand from a code point of view, as cache = True/False is more understandable than no-cache = True/False.
However, the if-query would then be more understandable:

```
if no-cache:
    base_command.extend(['--no-cache'])
```

I am curious to hear your opinion 😃

**Comment by mtlynch** [comment]
I try to avoid having "not" in variable names as I think the logic becomes confusing. I'm happy with us using a positive variable name internally and translating it to `-no-cache` for restic.

That said, I think `use_cache` would make it more obvious that the variable represents a boolean because `cache` sounds like it might store the location of a cache or the cached data itself.

**Comment by baurmatt** [comment]
Renamed it. Thanks for your input! :)

**Review by mtlynch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
