### PR TITLE
Allow forget to result to be empty

### LINKED ISSUE #93: forget throws exception for empty repository on JSON parse
If there are no snapshots, restic won't return anything:

```
$ RESTIC_PASSWORD=xxxxxx RESTIC_REPOSITORY=s3:s3.example.de/s3-backupper AWS_ACCESS_KEY_ID=yyyyyy AWS_SECRET_ACCESS_KEY=zzzzzz restic --json forget --keep-daily 7 --keep-weekly 4 --keep-monthly 3
$ echo $?
0
```

This currently leads to an exception because the JSON parser can't parse it:

```
Traceback (most recent call last):
  File "/home/mbaur/Sources/s3-backupper/.venv/lib/python3.9/site-packages/restic/internal/forget.py", line 60, in _parse_result
    return json.loads(result_lines[0])
  File "/home/mbaur/.linuxbrew/opt/python@3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/mbaur/.linuxbrew/opt/python@3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mbaur/.linuxbrew/opt/python@3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### PR DESCRIPTION
**Pull request by baurmatt**
Fixes #93.

### CODE REVIEW

**Comment by baurmatt** [comment]
ok, this build error isn't on me :D

**Comment by mtlynch** [comment]
Oh, sorry. The build failure is because it's trying to get the Coveralls auth token, but it can't because it's a forked PR, so CircleCI isn't exposing its secrets. I'll fix that.

**Comment by baurmatt** [comment]
@mtlynch Yep, that worked! Thanks! :)

**Review by mtlynch — APPROVED** [review]
LGTM, thanks!

**Comment by mtlynch** [comment]
@baurmatt - Whoops, sorry, I forgot to merge this.

**Pull request merged**
